My name is <b>Murat Çelik</b><br>
I am interested in Data Science<br>
I am a student of Computer Science in Hacettepe University
<br>
 <a href="https://www.linkedin.com/in/muratcelik35/">
  <img src="https://www.vargonen.com/blog/wp-content/uploads/2020/07/linkedin-ana-gorsel-.jpg" alt="Linkedin Account" style="width:84px;height:63px;float:left;">
</a> 
<br><br>
<h4><b>Date</b><br></h4>
&nbsp;&nbsp;&nbsp;&nbsp;26/02/2021 : Created Numpy notebook


 <img src="https://miro.medium.com/max/765/1*cyXCE-JcBelTyrK-58w6_Q.png" alt="Numpy" width="500" height="600"> 

<p1>Numpy (short for Numerical Python) provides an efficient interface to store and operate on dense data buffers.</p1>

In [276]:
#Please check the your version of NumPy
import numpy
numpy.__version__

'1.19.2'

In [277]:
#By convention, people in SciPy/PyData world will import NumPy using np as an alias
import numpy as np

If you write "np." and push the "TAB" button, you will see all contents of the numpy namespace

<h2>Creating Arrays from Python Lists</h2>

In [278]:
first_array = np.array([1,2,3,4,5])
first_array

array([1, 2, 3, 4, 5])

In [279]:
# Pay attention to the data types in the top and bottom
second_array = np.array([2.7,3.1, 4, 5,6 ])
second_array

array([2.7, 3.1, 4. , 5. , 6. ])

In [280]:
# If types do not match, NumPy will upcast if possible
print(first_array.dtype)
print(second_array.dtype)

int32
float64


In [281]:
# You can set type of data
x = np.array([1,2,3,4,5],dtype="float32")
x

array([1., 2., 3., 4., 5.], dtype=float32)

In [282]:
# nested lists result in multidimensional arrays
x = np.array([range(i,i+3) for i in [2,4,6]])
x

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

<h4>Creating Arrays from Scratch</h4>

In [283]:
# Create a length-10 integer array filled with zeros
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [284]:
np.zeros((3,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [285]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [286]:
np.full((3,3),3.14)

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [287]:
# Create an array filled with a linear sequence
x = np.arange(0,20,2)
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [288]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [289]:
# Random values between 0 and 1
np.random.random((4,4))

array([[0.56542131, 0.18327984, 0.14484776, 0.48805628],
       [0.35561274, 0.94043195, 0.76532525, 0.74866362],
       [0.90371974, 0.08342244, 0.55219247, 0.58447607],
       [0.96193638, 0.29214753, 0.24082878, 0.10029394]])

In [290]:
# Create 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0,1,(3,3))

array([[ 1.0996596 ,  0.65526373,  0.64013153],
       [-1.61695604, -0.02432612, -0.73803091],
       [ 0.2799246 , -0.09815039,  0.91017891]])

In [291]:
# random integer values in the interval
np.random.randint(0,10,(3,3))

array([[9, 4, 1],
       [5, 9, 7],
       [1, 3, 5]])

<h6>Identity Matrix </h6>

In [292]:
# Identity Matrix  
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [293]:
#Create an uninitialized array of three integers
#The values will be whatever happens to already exist at that
#memory location
np.empty(3)

array([1., 2., 3.])

<h2>NumPy Standard Data Types</h2>
 <img src="https://miro.medium.com/max/1330/1*s6gKy2DZ_300dgAeHPgjkQ.png" alt="Standard NumPy data types" width="500" height="600"> 

In [294]:
x = np.zeros(10,dtype='float16') 
y = np.zeros(10,dtype= np.float16)
print(x)
print(y)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


<h2>The Basics of NumPy Arrays</h2>

<p1><i>&nbsp;&nbsp;&nbsp;&nbsp;Attributes of arrays</i> <br>
Determining the size, shape, memory consumption, and data types of arrays</p1><br>
<p1><i>&nbsp;&nbsp;&nbsp;&nbsp;Indexing of arrays</i> <br>
Getting and setting the value of individual array elements</p1><br>
<p1><i>&nbsp;&nbsp;&nbsp;&nbsp;Slicing of arrays</i> <br>
Getting and setting smaller subarrays within a larger array</p1><br>
<p1><i>&nbsp;&nbsp;&nbsp;&nbsp;Reshaping of arrays</i> <br>
Changing the shape of a given array</p1><br>
<p1><i>&nbsp;&nbsp;&nbsp;&nbsp;Joining and splitting of arrays</i> <br>
Combining multiple arrays into one, and splitting one array into many</p1>

<h4>NumPy Array Attributes</h4><br>
ndarray.ndim<br>
ndarray.shape<br>
ndarray.size<br>
ndarray.dtype<br>
ndarray.itemsize<br>
ndarray.nbytes

In [295]:
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4)) 
x3 = np.random.randint(10, size=(3, 4, 5)) 
print("One-dimensional array\n")
print(x1)
print("\nTwo-dimensional array\n")
print(x2)
print("\nThree-dimensional array\n")
print(x3)

One-dimensional array

[7 3 6 6 7 9]

Two-dimensional array

[[1 9 6 0]
 [3 8 4 1]
 [4 5 0 3]]

Three-dimensional array

[[[1 4 4 4 0]
  [0 8 4 6 9]
  [3 3 2 1 2]
  [1 3 4 1 1]]

 [[0 7 8 4 3]
  [5 6 3 2 9]
  [8 1 4 0 8]
  [3 9 5 5 1]]

 [[7 8 6 4 7]
  [3 5 3 6 4]
  [7 3 0 5 9]
  [3 7 5 5 8]]]


In [296]:
np.random.seed(0)
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4)) 
x3 = np.random.randint(10, size=(3, 4, 5)) 
print("One-dimensional array\n")
print(x1)
print("\nTwo-dimensional array\n")
print(x2)
print("\nThree-dimensional array\n")
print(x3)

One-dimensional array

[5 0 3 3 7 9]

Two-dimensional array

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]

Three-dimensional array

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [297]:
print("One-dimensional array\n")
print("x3 ndim: ", x1.ndim)
print("x3 shape:", x1.shape)
print("x3 size: ", x1.size)
print("x3 dtype: ", x1.dtype)
print("x3 itemsize:", x1.itemsize,"bytes")
print("x3 nbytes: ", x1.nbytes,"bytes")
print("\nTwo-dimensional array\n")
print("x3 ndim: ", x2.ndim)
print("x3 shape:", x2.shape)
print("x3 size: ", x2.size)
print("x3 dtype: ", x2.dtype)
print("x3 itemsize:", x2.itemsize,"bytes")
print("x3 nbytes: ", x2.nbytes,"bytes")
print("\nThree-dimensional array\n")
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("x3 dtype: ", x3.dtype)
print("x3 itemsize:", x3.itemsize,"bytes")
print("x3 nbytes: ", x3.nbytes,"bytes")

One-dimensional array

x3 ndim:  1
x3 shape: (6,)
x3 size:  6
x3 dtype:  int32
x3 itemsize: 4 bytes
x3 nbytes:  24 bytes

Two-dimensional array

x3 ndim:  2
x3 shape: (3, 4)
x3 size:  12
x3 dtype:  int32
x3 itemsize: 4 bytes
x3 nbytes:  48 bytes

Three-dimensional array

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
x3 dtype:  int32
x3 itemsize: 4 bytes
x3 nbytes:  240 bytes


In [298]:
# np.random.seed(0) makes the random numbers predictabl. 
# more details https://stackoverflow.com/questions/21494489/what-does-numpy-random-seed0-do
np.random.seed(0)
first = np.random.randint(10, size=6)
print("first array \n",first)
np.random.seed(0)
second = np.random.randint(10, size=6)
print("second array \n",second)
third = np.random.randint(10, size=6)
print("third array \n",third)

first array 
 [5 0 3 3 7 9]
second array 
 [5 0 3 3 7 9]
third array 
 [3 5 2 4 7 6]


One important—and extremely useful—thing to know about array slices is that they
return views rather than copies of the array data. This is one area in which NumPy
array slicing differs from Python list slicing: in lists, slices will be copies.

In [299]:
x2 = np.array([[12,5 ,2 ,4],[ 7 ,6 ,8 ,8],[ 1 ,6 ,7 ,7]])
x2_sub = x2[:2,:2]
x2_sub[0, 0] = 99
print(x2_sub)
print()
print(x2)

[[99  5]
 [ 7  6]]

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [300]:
x2 = np.array([[12,5 ,2 ,4],[ 7 ,6 ,8 ,8],[ 1 ,6 ,7 ,7]])
x2_sub = x2[:2,:2].copy()
x2_sub[0, 0] = 99
print(x2_sub)
print()
print(x2)

[[99  5]
 [ 7  6]]

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


<h2>Reshaping of Arrays</h2>

In [301]:
grid = np.arange(1,10)
grid_reshape = grid.reshape(3,3)
print(grid)
print()
print(grid_reshape)

[1 2 3 4 5 6 7 8 9]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


You can do this with the reshape method, or more easily by making use of the <b>newaxis</b> keyword within a slice operation:

In [302]:
x = np.array([1,2,3,4,5])
x_vertical = x.reshape((5,1)) # row vector via reshape
x_vertical_newaxis = x[:,np.newaxis] # row vector via newaxis
print(x)
print()
print(x_vertical)
print()
print(x_vertical_newaxis)
print()

[1 2 3 4 5]

[[1]
 [2]
 [3]
 [4]
 [5]]

[[1]
 [2]
 [3]
 [4]
 [5]]



<h2> Array Concatenation and Splitting </h2>
All of the preceding routines worked on single arrays. It’s also possible to combine
multiple arrays into one, and to conversely split a single array into multiple arrays.

<h4>Concatenation of arrays</h4><br>
np.concatenate <br>
np.vstack<br>
np.hstack

In [303]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [304]:
grid = np.array([[1, 2, 3],
                [4, 5, 6]])
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [305]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [306]:
np.vstack([x,grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [307]:
y = np.array([[99],[99]])
np.hstack([grid,y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

In [308]:
np.dstack([grid,grid]) #np.dstack will stack arrays along the third axis.

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

<h4>Splitting of arrays </h4><br>
np.split<br>
np.hsplit<br>
np.vsplit

In [309]:
x= [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [310]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [311]:
upper,lower = np.vsplit(grid,[2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [312]:
upper,lower = np.hsplit(grid,[2])
print(upper)
print(lower)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


<h2>Computation on NumPy Arrays</h2>

In [313]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [314]:
x+5

array([ 6,  7,  8,  9, 10])

In [315]:
x*2

array([ 2,  4,  6,  8, 10])

In [316]:
x/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [317]:
x-5

array([-4, -3, -2, -1,  0])

In [318]:
x**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [319]:
x//2

array([0, 1, 1, 2, 2], dtype=int32)

In [320]:
x % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [321]:
y = np.array([-1,4,-3,-5,2])
y

array([-1,  4, -3, -5,  2])

In [322]:
np.abs(y)

array([1, 4, 3, 5, 2])

In [323]:
z = np.array([0, 30, 45, 60, 90])
z

array([ 0, 30, 45, 60, 90])

<h6>Trigonometric functions</h6>

In [324]:
np.sin(z*np.pi/180)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [325]:
np.cos(z*np.pi/180)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [326]:
np.tan(z*np.pi/180)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [327]:
theta = np.array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])
theta

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [328]:
np.arcsin(theta)/np.pi*180

array([ 0.        , 30.        , 44.9999999 , 59.99999957, 90.        ])

<h6>Exponents and logarithms</h6>

In [329]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [330]:
print("e^x : ",np.exp(x))

e^x :  [ 2.71828183  7.3890561  20.08553692]


In [331]:
print("2^x : ",np.exp2(x))

2^x :  [2. 4. 8.]


In [332]:
print("a^x : ",np.power(3,x))

a^x :  [ 3  9 27]


In [333]:
x = np.array([2,4,32,128])
y = np.array([1,10,100,1000])
z = np.array([2.71828183  ,7.3890561,  20.08553692])
print(x,"\n",y,"\n",z)

[  2   4  32 128] 
 [   1   10  100 1000] 
 [ 2.71828183  7.3890561  20.08553692]


In [334]:
print("ln(x) =", np.log(z))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(y))

ln(x) = [1. 2. 3.]
log2(x) = [1. 2. 5. 7.]
log10(x) = [0. 1. 2. 3.]


<h2>Advanced Features</h2>

<h4>Aggregates</h4>

In [335]:
# calling reduce on the add ufunc returns the sum of all elements in the array
x = np.arange(1, 6)
np.add.reduce(x)

15

In [336]:
# calling reduce on the multiply ufunc results in the product of all array elements
np.multiply.reduce(x)

120

In [337]:
#If we’d like to store all the intermediate results of the computation, we can instead use accumulate
print(np.add.accumulate(x))
print(np.multiply.accumulate(x))


[ 1  3  6 10 15]
[  1   2   6  24 120]


<h4>Outer products</h4>

In [338]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

<h4>Summing the Values in an Array</h4>

In [339]:
L = np.random.random(100)
L

array([0.05671298, 0.27265629, 0.47766512, 0.81216873, 0.47997717,
       0.3927848 , 0.83607876, 0.33739616, 0.64817187, 0.36824154,
       0.95715516, 0.14035078, 0.87008726, 0.47360805, 0.80091075,
       0.52047748, 0.67887953, 0.72063265, 0.58201979, 0.53737323,
       0.75861562, 0.10590761, 0.47360042, 0.18633234, 0.73691818,
       0.21655035, 0.13521817, 0.32414101, 0.14967487, 0.22232139,
       0.38648898, 0.90259848, 0.44994999, 0.61306346, 0.90234858,
       0.09928035, 0.96980907, 0.65314004, 0.17090959, 0.35815217,
       0.75068614, 0.60783067, 0.32504723, 0.03842543, 0.63427406,
       0.95894927, 0.65279032, 0.63505887, 0.99529957, 0.58185033,
       0.41436859, 0.4746975 , 0.6235101 , 0.33800761, 0.67475232,
       0.31720174, 0.77834548, 0.94957105, 0.66252687, 0.01357164,
       0.6228461 , 0.67365963, 0.971945  , 0.87819347, 0.50962438,
       0.05571469, 0.45115921, 0.01998767, 0.44171092, 0.97958673,
       0.35944446, 0.48089353, 0.68866118, 0.88047589, 0.91823

In [340]:
print(sum(L))
%timeit sum(L)

52.77225132363466
28.8 µs ± 2.19 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [341]:
# NumPy’s version of the operation is computed much more quickly
print(np.sum(L))
%timeit np.sum(L)

52.77225132363466
5.54 µs ± 396 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


<h4>Other Aggregation functions</h4>

In [342]:
np.min(L)

0.009356704856532616

In [343]:
np.max(L)

0.9952995676778876

In [344]:
np.mean(L)

0.5277225132363467

In [345]:
np.median(L)

0.5289253545001078

In [346]:
np.std(L)

0.27764795589618535

In [347]:
np.prod(L)

8.770446194283112e-40

In [348]:
np.var(L)

0.07708838741333009

In [349]:
np.percentile(L,25)

0.3248206737045679

In [350]:
np.percentile(L,50)

0.5289253545001078

In [351]:
np.percentile(L,75)

0.7520412793801023

<h2>Computation on Arrays</h2>

In [352]:
a = np.array([1,2,3,4,5])
b = np.array([11,12,13,14,15])
a+b

array([12, 14, 16, 18, 20])

In [353]:
a*b

array([11, 24, 39, 56, 75])

In [354]:
b/a

array([11.        ,  6.        ,  4.33333333,  3.5       ,  3.        ])

In [355]:
a < 3

array([ True,  True, False, False, False])

In [356]:
a == 3

array([False, False,  True, False, False])

In [357]:
a>=3

array([False, False,  True,  True,  True])

In [358]:
np.any(a>8)

False

In [359]:
np.any(b>8)

True

In [360]:
np.all(a>=1)

True

In [361]:
np.all(b>12)

False

<h2>Exploring Fancy Indexing</h2>

In [362]:
x = np.random.randint(100,size=10)
x

array([52, 67, 61, 14, 96,  4, 67, 11, 86, 77])

In [363]:
a = [3,5,7]
x[a]

array([14,  4, 11])

In [364]:
x = np.random.randint(100,size=9)
x

array([75, 56, 16, 24, 29, 21, 25, 80, 60])

In [365]:
b = np.array([[0,2],[1,0],[2,2]])
x[b]

array([[75, 16],
       [56, 75],
       [16, 16]])

<h2>Sorting</h2>

In [366]:
x = np.array([5,1,-5,15,82,335,42,51,25,36,-25,25,-52,82])
x

array([  5,   1,  -5,  15,  82, 335,  42,  51,  25,  36, -25,  25, -52,
        82])

In [367]:
# without modifying
np.sort(x)

array([-52, -25,  -5,   1,   5,  15,  25,  25,  36,  42,  51,  82,  82,
       335])

In [368]:
x

array([  5,   1,  -5,  15,  82, 335,  42,  51,  25,  36, -25,  25, -52,
        82])

In [369]:
#with modifying
x.sort()
x

array([-52, -25,  -5,   1,   5,  15,  25,  25,  36,  42,  51,  82,  82,
       335])

In [370]:
# argsort instead returns the indices of the sorted elements
x = np.array([5,1,-5,15,82,335,42,51,25,36,-25,25,-52,82])
i = x.argsort()
i

array([12, 10,  2,  1,  0,  3,  8, 11,  9,  6,  7,  4, 13,  5],
      dtype=int64)

In [371]:
x = np.array([[6 ,3, 7, 4, 6, 9],
[2 ,6 ,7 ,4 ,3 ,7],
[7 ,2 ,5 ,4 ,1 ,7],
[5 ,1 ,4 ,0 ,9 ,5]])
x

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [372]:
np.sort(x,axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [373]:
np.sort(x,axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

In [374]:
x = np.array([5,1,-5,15,82,335,42,51,25,36,-25,25,-52,82])
x

array([  5,   1,  -5,  15,  82, 335,  42,  51,  25,  36, -25,  25, -52,
        82])

<h1>Reference</h1>
<h3><blockquote>Book</blockquote></h3>
Python Data Science Handbook: Essential Tools for Working with Data
<h3><blockquote>Web Sites</blockquote></h3>
<a href="https://numpy.org/doc/stable/contents.html">NumPy Documentation</a>