for <a href="https://github.com/MuratCelik3506/Data_Science_WorkSpace/blob/main/NoteBook/Python/Pandas/">  Pandas </a>
## My name is Murat Çelik
    I am interested in Data Science 
    I am a student of Computer Science in Hacettepe University
 <a href="https://www.linkedin.com/in/muratcelik35/">
     Contact:

</a> 
<br><br>
<h4><b>Date</b><br></h4>
&nbsp;&nbsp;&nbsp;&nbsp;02/03/2021 : Created Pandas notebook



<img src="../Pandas/pandas.png" alt="Pandas" width="500" height="600"> 

# Combining Datasets

### Concat and Append

In [2]:
import numpy as np
import pandas as pd

In [3]:
def make_df(cols, ind):
    """Quickly make a DataFrame"""
    data = {c: [str(c) + str(i) for i in ind]
    for c in cols}
    return pd.DataFrame(data, ind)
# example DataFrame
make_df('ABC', range(3))

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

#### Recall: Concatenation of NumPy Arrays

In [4]:
x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
x = [[1,2],[3,4]]
x_X = np.concatenate([x,x])

In [6]:
x_X

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [7]:
x_y = np.concatenate([x,x],axis=1)

In [8]:
x_y

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

#### Simple Concatenation with pd.concat
 
    Signature in Pandas v0.18
    
pd.concat(objs, axis=0, join='outer', join_axes=None, ignore_index=False,
keys=None, levels=None, names=None, verify_integrity=False,
copy=True)

In [9]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6])
pd.concat([ser1, ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [12]:
# Axis
df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [3, 4])
print(pd.concat([df1, df2]))

    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4


In [18]:
df3 = make_df('AB', [0, 1])
df4 = make_df('CD', [0, 1])
print(pd.concat([df3, df4], axis=1))

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1


        Catching the repeats as an error
If you’d like to simply verify that the indices in the
result of pd.concat() do not overlap, you can specify the verify_integrity flag.

In [10]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[2, 3, 6])
pd.concat([ser1, ser2])

1    A
2    B
3    C
2    D
3    E
6    F
dtype: object

In [21]:
try : 
    ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
    ser2 = pd.Series(['D', 'E', 'F'], index=[2, 3, 6])
    pd.concat([ser1, ser2],verify_integrity=True)
except ValueError as e:
    print("ValueError",e)

ValueError Indexes have overlapping values: Int64Index([2, 3], dtype='int64')


        Ignoring the index. 
Sometimes the index itself does not matter, and you would prefer
it to simply be ignored. You can specify this option using the ignore_index flag

In [22]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[2, 3, 6])
pd.concat([ser1, ser2],ignore_index=True)

0    A
1    B
2    C
3    D
4    E
5    F
dtype: object

        Adding MultiIndex keys. 
Another alternative is to use the keys option to specify a label
for the data sources; the result will be a hierarchically indexed series containing the
data:

In [24]:
df5 = make_df('ABC', [1, 2])
df6 = make_df('BCD', [1, 2])
pd.concat([df5, df6], keys=['x', 'y'])

A   B   C    D
x 1   A1  B1  C1  NaN
  2   A2  B2  C2  NaN
y 1  NaN  B1  C1   D1
  2  NaN  B2  C2   D2

In [26]:
pd.concat([df5,df6],join='inner')

B   C
1  B1  C1
2  B2  C2
1  B1  C1
2  B2  C2

"join_axes" was deprecated in version 0.25 for some reason. You can achieve the same effect by reindexing.

<a href="https://stackoverflow.com/questions/61362942/concat-got-an-unexpected-keyword-argument-join-axes">more information</a>

In [29]:
pd.concat([df5, df6], join_axes=[df5.columns]) # 

TypeError: concat() got an unexpected keyword argument 'join_axes'

In [32]:
df5 = make_df('ABC', [1, 2])
df6 = make_df('BCD', [1, 2])
df5

A   B   C
1  A1  B1  C1
2  A2  B2  C2

### The append() method
Because direct array concatenation is so common, Series and DataFrame objects
have an append method that can accomplish the same thing in fewer keystrokes. For
example, rather than calling pd.concat([df1, df2]), you can simply call
df1.append(df2)



In [36]:
df5.append(df6)

A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
1  NaN  B1  C1   D1
2  NaN  B2  C2   D2

Keep in mind that unlike the append() and extend() methods of Python lists, the
append() method in Pandas does not modify the original object—instead, it creates a
new object with the combined data. It also is not a very efficient method, because it
involves creation of a new index and data buffer. Thus, if you plan to do multiple
append operations, it is generally better to build a list of DataFrames and pass them all
at once to the concat() function.

## Merge and Join
One essential feature offered by Pandas is its high-performance, in-memory join and
merge operations.

#### Categories of Joins
The pd.merge() function implements a number of types of joins: the one-to-one,
many-to-one, and many-to-many joins. All three types of joins are accessed via an
identical call to the pd.merge() interface; the type of join performed depends on the
form of the input data.

In [41]:
# One-to-one joins
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
'hire_date': [2004, 2008, 2012, 2014]})
print(df1)
print()
print(df2)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014


In [43]:
df3 = pd.merge(df1,df2)
df3

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

#### Many-to-one joins
Many-to-one joins are joins in which one of the two key columns contains duplicate
entries. For the many-to-one case, the resulting DataFrame will preserve those duplicate
entries as appropriate.

In [44]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
'supervisor': ['Carly', 'Guido', 'Steve']})
df4

group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve

In [45]:
pd.merge(df3,df4)

employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve

#### Many-to-many joins
Many-to-many joins are a bit confusing conceptually, but are nevertheless well
defined. If the key column in both the left and right array contains duplicates, then
the result is a many-to-many merge.

In [46]:
df5 = pd.DataFrame({'group': ['Accounting', 'Accounting',
'Engineering', 'Engineering', 'HR', 'HR'],'skills': ['math', 'spreadsheets', 'coding', 'linux',
'spreadsheets', 'organization']})
df5

group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization

In [47]:
df1

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [48]:
pd.merge(df1,df5)

employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization

### Specification of the Merge Key
#### The on keyword for Merge
Most simply, you can explicitly specify the name of the key column using the on keyword,
which takes a column name or a list of column names:

In [50]:
print(df1)
print()
print(df2)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014


In [51]:
pd.merge(df1, df2, on='employee')

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [52]:
pd.merge(df1, df2)

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [53]:
df6 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
'food': ['fish', 'beans', 'bread']},
columns=['name', 'food'])
df7 = pd.DataFrame({'name': ['Mary', 'Joseph'],
'drink': ['wine', 'beer']},
columns=['name', 'drink'])
print(df6); 
print();print(df7); print();print(pd.merge(df6, df7))

    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread

     name drink
0    Mary  wine
1  Joseph  beer

   name   food drink
0  Mary  bread  wine


In [54]:
pd.merge(df6, df7,how="inner")

name   food drink
0  Mary  bread  wine

In [55]:
pd.merge(df6, df7,how="outer")

name   food drink
0   Peter   fish   NaN
1    Paul  beans   NaN
2    Mary  bread  wine
3  Joseph    NaN  beer

In [56]:
pd.merge(df6, df7,how="left")

name   food drink
0  Peter   fish   NaN
1   Paul  beans   NaN
2   Mary  bread  wine

In [57]:
pd.merge(df6, df7,how="right")

name   food drink
0    Mary  bread  wine
1  Joseph    NaN  beer